version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # mysql -h 127.0.0.1 -p
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      # This directory is used to initialise the database. Use read-only mount
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro